### ISSUE TITLE
Get null pointer exception when trying to run

### ISSUE THREAD

**Issue by GlenHertz** [babyman/tw2md#1]
I've tried to run it in a few different ways:

```bash
/usr/lib/jvm/java-11-openjdk/bin/java -jar tw2md.jar $PWD/tw5 $PWD/newdir
/usr/lib/jvm/java-11-openjdk/bin/java -jar tw2md.jar tw5 alreadycreatedemptydir
/usr/lib/jvm/java-11-openjdk/bin/java -jar tw2md.jar tw5/tw5.html alreadycreatedemptydir
```

But I always get the error:

```
java.lang.NullPointerException
	at ca.codepit.tw2md.Main.call(Main.java:188)
	at ca.codepit.tw2md.Main.call(Main.java:27)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at ca.codepit.tw2md.Main.main(Main.java:168)
```

I'm on Linux running Java 11.  In the Readme it looks like the first argument is a directory which is a bit confusing because my TW5.html file is one file.  Is it expected tiddlers are exported to each their own file first?

**Comment by GlenHertz** [comment]
Looking at the testcases it seems to need 1 `.tid` file per tiddler.  I'm using TW 5.2 and the export file only has JSON, CSV, and HTML as an option.  Maybe I need to try an older version of TW.

**Comment by babyman** [comment]
@GlenHertz firstly thank you for trying this code out and taking the time to report this issue!!

Some background, I had been running tiddlywiki as a server on my mac (it's been a long time since I used the single page version),

```bash
tiddlywiki --version
5.1.23

# launching the wiki (server)
tiddlywiki ./myWiki --server 9090
syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
Serving on http://127.0.0.1:9090
```

The wiki directory has a file called `tiddlywiki.info` in it and a `tiddlers` directory with the tiddlers (\*.tid) files.

I could recreate the NullPointerException locally (easily) with:

```bash
java -jar tw2md.jar ./myWiki ./outDir
```

Rookie mistake, I left some uninitialized variables because I was always setting them for my local migration.

I have pushed a fix and new release jar, let me know how this works for you.

Evan
